### ISSUE TITLE
add terms1_terms2_cardinality3 and terms1_date_histogram2_cardinality3

### ISSUE THREAD

**Issue by doogyb** [nestauk/asf_hp_market_tracker#159]

**Comment by mindrones** [comment]
These were originally needed to get
- average number of certifications per installer per region
- average number of certifications per installer per calendar_interval

but as we can see in `be/test/routes/api/terms1_cardinality2/09.json`, the `average` is ~1 with a very low `variance` (see [1]), so these would probably generate not very interesting charts so we agreed to downgrade the priority of this and revisit it after having implemented filtering.

[1]
```
"stats": {
	"count": 2410,
	"min": 0,
	"max": 7,
	"avg": 1.0427385892116183,
	"sum": 2513,
	"sum_of_squares": 2995,
	"variance": 0.15543482378058224,
	"variance_population": 0.15543482378058224,
	"variance_sampling": 0.15549934633092702,
	"std_deviation": 0.3942522337039858,
	"std_deviation_population": 0.3942522337039858,
	"std_deviation_sampling": 0.3943340542369211,
	"std_deviation_bounds": {
		"upper": 1.83124305661959,
		"lower": 0.2542341218036467,
		"upper_population": 1.83124305661959,
		"lower_population": 0.2542341218036467,
		"upper_sampling": 1.8314066976854604,
		"lower_sampling": 0.25407048073777616
	}
}
```
